/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package people

class App {
      fun readOption():Int {
            return try {
                readLine()!!.toInt() 
            } catch (e:NumberFormatException) {
                println("Formato de opcção não aceito.")
                4
            } catch (e:NullPointerException) {
                println("Err: Erro não reconhecido.")
                -1
            }
        }
    fun printOptions() {
      
        println("-------------------------------------")
        println("| 1) Create new user----------------|")
        println("| 2) See last register--------------|")
        println("| 3) See all Registers--------------|")
        println("| 4) Save and Quit------------------|")
        println("| 5) Quit w/o sag-------------------|")
        println("-------------------------------------")
        println("Choose [default 4]: ")

    }
    
    fun run() {
        this.printOptions()
        print(this.readOption())
    }
}

fun main() {
    App().run();
}


